# Generated by Django 4.1.4 on 2023-01-05 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lisitng',
            new_name='Listing',
        ),
    ]
